# neu-Fabric 项目组所有
# author: zz
# time: 2018-04-30
# 该配置文件描述了fabrci的网络拓扑和组织结构关系
# 采用yaml语法描述，整体分为两大类：OrdererOrgs和PeerOrgs
# OrdererOrgs描述了order组织结构，PeerOrgs描述了peer组织结构
# 下面是示例文件

OrdererOrgs:
  - Name: Orderer # Name为组织的名称
    Domain: example.com # Domain为阻止的域名
    CA: # CA为阻止的CA信息
      Country: CH
      Province: LiaoNing
      Locality: ShenYang
    # Specs字段指定了这个组织下面的节点，每个节点包含两个字段：Hostname和CommonName，其中HostName是必须的
    Specs:
      - Hostname: foo
        CommonName: foo.example.com
      - Hostname: bar
        CommonName: bar.example.com

# 
PeerOrgs:
  - Name: org1
    Domain: org1.example.com
    CA:
      Country: CH
      Province: LiaoNing
      Locality: ShenYang
    # Template使用模板自动生成制定个数的peer
    Template:
      Count: 5
    # Users生成指定个数的普通用户
    Users:
      Count: 2
  - Name: org2
    Domain: org2.example.com
    CA:
      Country: CH
      Province: LiaoNing
      Locality: ShenYang
    Template:
      Count: 2
    Users:
      Count: 1